name: Heroku/Docker build

on: [push]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    - name: Docker Registry Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Building Docker Image
      env:
        CONTAINER_IMAGE_NAME: reachhigh-be
        # DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        # PORT: ${{ secrets.PORT }}
        # SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run:
        docker build --no-cache -t $CONTAINER_IMAGE_NAME:latest .
    - name: Heroku Login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    # - name: Push Docker Image to Registry
    #   env:
    #     USERNAME: ekpo3
    #     CONTAINER_IMAGE_NAME: reachhigh-be
    #     # DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
    #   run: docker push $USERNAME/$CONTAINER_IMAGE_NAME:latest




    # - name: Shell Lint
    #   uses: shinofumijp/bin/shellcheck@master
    #   with:
    #     args: entrypoint.sh
    # - name: Publish Filter
    #   uses: shinofumijp/bin/filter@master
    #   with:
    #     args: branch master
    # - name: Build
    #   uses: acejam/docker-1/cli@master
    #   with:
    #     args: build -t heroku .
    # - name: Login
    #   uses: acejam/docker-1/login@master
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Tag
    #   uses: acejam/docker-1/tag@master
    #   with:
    #     args: heroku github/heroku --no-latest
    # - name: Publish
    #   run: docker push ekpo3/heroku