name: Heroku/Docker build

on: [push]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    - name: Building Docker Image
      env:
        CONTAINER_IMAGE_NAME: reachhigh-be
      run:
        docker build --no-cache -t $CONTAINER_IMAGE_NAME:latest .
    - name: Heroku Registry Login
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
    - name: Push Image To Heroku
      env:
        CONTAINER_IMAGE_NAME: reachhigh-be
      run:
        docker tag $CONTAINER_IMAGE_NAME:latest registry.heroku.com/$CONTAINER_IMAGE_NAME/web && docker push registry.heroku.com/$CONTAINER_IMAGE_NAME/web
    - name: Heroku CLI Credentials
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        echo "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_API_KEY\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_API_KEY" > ~/.netrc
    - name: Heroku Container Login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: Heroku Container Push
      uses: actions/heroku@master
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: 
          echo "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_API_KEY\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_API_KEY" > ~/.netrc && container:push -a $HEROKU_APP_NAME web
    - name: Heroku Container Release
      uses: actions/heroku@master
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      with:
        args: container:release -a $HEROKU_APP_NAME web




    # - name: Building Docker Image
    #   env:
    #     CONTAINER_IMAGE_NAME: reachhigh-be
    #     # DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
    #     # PORT: ${{ secrets.PORT }}
    #     # SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #   run:
    #     docker build --no-cache -t $CONTAINER_IMAGE_NAME:latest .
    # - name: Docker Registry Login
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    # - name: Push Docker Image to Registry
    #   env:
    #     USERNAME: ekpo3
    #     CONTAINER_IMAGE_NAME: reachhigh-be
    #     # DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
    #   run: docker push $USERNAME/$CONTAINER_IMAGE_NAME:latest
    # - name: Shell Lint
    #   uses: shinofumijp/bin/shellcheck@master
    #   with:
    #     args: entrypoint.sh
    # - name: Publish Filter
    #   uses: shinofumijp/bin/filter@master
    #   with:
    #     args: branch master
    # - name: Build
    #   uses: acejam/docker-1/cli@master
    #   with:
    #     args: build -t heroku .
    # - name: Login
    #   uses: acejam/docker-1/login@master
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Tag
    #   uses: acejam/docker-1/tag@master
    #   with:
    #     args: heroku github/heroku --no-latest
    # - name: Publish
    #   run: docker push ekpo3/heroku