name: Heroku/Docker build

on: [push]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    # - name: Shell Lint
    #   uses: shinofumijp/bin/shellcheck@master
    #   with:
    #     args: entrypoint.sh
    # - name: Publish Filter
    #   uses: shinofumijp/bin/filter@master
    #   with:
    #     args: branch master
    - name: Build
      run: docker build -t heroku .
    - name: Login
      uses: azure/docker-login@v1
      env:
        username: ${{ secrets.DOCKER_PASSWORD }}
        password: ${{ secrets.DOCKER_USERNAME }}
    # - name: Tag
    #   uses: shinofumijp/docker/tag@master
    #   with:
    #     args: heroku github/heroku --no-latest
    # - name: Publish
    #   uses: shinofumijp/docker/cli@master
    #   with:
    #     args: push github/heroku
