name: Heroku/Docker build

on: [push]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    # - name: Shell Lint
    #   uses: shinofumijp/bin/shellcheck@master
    #   with:
    #     args: entrypoint.sh
    # - name: Publish Filter
    #   uses: shinofumijp/bin/filter@master
    #   with:
    #     args: branch master
    - name: Build
      uses: acejam/docker-1/docker/cli@master
      with:
        args: build -t heroku .
    - name: Login
      uses: acejam/docker-1/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag
      uses: acejam/docker-1/docker/tag@master
      with:
        args: heroku github/heroku --no-latest
    - name: Publish
      uses: acejam/docker-1/docker/cli@master
      with:
        args: push github/heroku


    # - name: Build
    #   run: docker build -t heroku .
    # - name: Login
    #   uses: azure/docker-login@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
